version: 1
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Setup custom environment variables
          command: echo $GOOGLE_SERVICES_JSON | base64 --decode > app/google-services.json
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      # Unit tests for all modules
      - run:
          name: Run App Module Unit Tests
          command: ./gradlew :app:testDebugUnitTest
      - store_artifacts:
          path: app/build/reports
      - store_test_results:
          path: app/build/test-results
      - run:
          name: Run Concierge Module Unit Tests
          command: ./gradlew :concierge:testDebugUnitTest
      - store_artifacts:
          path: concierge/build/reports
      - store_test_results:
          path: concierge/build/test-results
      - run:
          name: Run Oracle Module Unit Tests
          command: ./gradlew :oracle:testDebugUnitTest
      - store_artifacts:
          path: oracle/build/reports
      - store_test_results:
          path: oracle/build/test-results
      - run:
          name: Run Pico Module Unit Tests
          command: ./gradlew :pico:testDebugUnitTest
      - store_artifacts:
          path: pico/build/reports
      - store_test_results:
          path: pico/build/test-results
      - run:
          name: Run Base Module Unit Tests
          command: ./gradlew :base:testDebugUnitTest
      - store_artifacts:
          path: base/build/reports
      - store_test_results:
          path: base/build/test-results